### ISSUE TITLE
Could you release a new version?

### ISSUE THREAD

**Issue by madejejej** [Paxa/fast_excel#16]
Hey!

It's been a long time since the last release (20 Jun) and there were a few pull requests that improved the performance. We'd really appreciate it if you released a new version since we'd love to include `fast_excel` in one of our gem's dependencies .

**Comment by Paxa** [comment]
Will do it, mean while you can include it from github:
```
gem 'fast_excel', github: 'Paxa/fast_excel'
```

**Comment by Paxa** [comment]
Released version 0.2.2

**Comment by madejejej** [comment]
Unfortunately you can't set github source in a gemspec so we really needed the new release. Thanks a lot!

**Comment by Paxa** [comment]
Usually I make it as:
```ruby
source 'https://rubygems.org'

# to avoid ssl warnings
git_source(:github) do |repo_name|
  "https://github.com/#{repo_name}.git"
end

...

gem 'fast_excel', github: 'paxa/fast_excel'

```

**Comment by AlexWayfer** [comment]
Simple way: https://github.com/bundler/bundler/issues/4978#issuecomment-255022764
