### ISSUE TITLE
undefined method `constant_memory?' for nil:NilClass

### ISSUE THREAD

**Issue by GarPit** [Paxa/fast_excel#20]
I have this issue when trying to find existing worksheet and then write to it:

    NoMethodError:
       undefined method `constant_memory?' for nil:NilClass
     # /Users/gradus/.rvm/gems/ruby-2.3.1/bundler/gems/fast_excel-07292bd3b116/lib/fast_excel.rb:403:in `write_value'
     # /Users/gradus/.rvm/gems/ruby-2.3.1/bundler/gems/fast_excel-07292bd3b116/lib/fast_excel.rb:397:in `block in write_row'

Code to repeat:

    workbook = FastExcel.open(destination, constant_memory: true)
    worksheet = workbook.get_worksheet_by_name('Report 1')
    worksheet.write_row(0, ['1'])

**Comment by Paxa** [comment]
Unfortunately libxlsxwriter doesn't support opening and editing existing files. It can only create new files

I added nice error message and make `get_worksheet_by_name` work for unsaved file

**Comment by Paxa** [comment]
Thank you for your report!
