### ISSUE TITLE
New tagged release on RubyGems

### ISSUE THREAD

**Issue by hbergren** [Paxa/fast_excel#23]
Hi,

I was hoping that `0.2.4` could be pushed up to [RubyGems](https://rubygems.org/gems/fast_excel/)

Additionally, if it's easy to upgrade `libxlsxwriter` to the latest version ([0.7.7](https://github.com/jmcnamara/libxlsxwriter/releases/tag/RELEASE_0.7.7)), then that would be appreciated. I see the diff for `0.7.6` => `0.7.7` is non-trivial though, so I'm not sure what that involves in terms of testing / validation.

**Comment by Paxa** [comment]
Sorry, already fixed (version 0.2.5 with libxlsxwriter 0.7.7)
