### ISSUE TITLE
Exceeding maximum number of URLs

### ISSUE THREAD

**Issue by iamtheschmitzer** [Paxa/fast_excel#25]
I have hit the limit of maximum number of URLs.  From lib/fast_excel/binding.rb

> MAX_NUMBER_URLS = 65530

It looks like this is a libxlswriter limitation.  Is there a workaround to this?

**Comment by iamtheschmitzer** [comment]
No, this is an Excel internal per worksheet limit.

**Comment by ye-lin-aung** [comment]
I noticed that we can pass string_to_urls: False in C to disable converting string to urls but I don't find anywhere to add that options in FastExcel
