### ISSUE TITLE
Errors encountered when test example.rb

### ISSUE THREAD

**Issue by lsq** [Paxa/fast_excel#29]
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/ffi-1.10.0/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/fast_excel-0.2.5/libxlsxwriter/lib/libxlsxwriter.so': dlopen failed: cannot locate symbol "fopen64" referenced by "/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/fast_excel-0.2.5/libxlsxwriter/lib/libxlsxwriter.so"... (LoadError)

**Comment by Paxa** [comment]
What system do you use? Linux?

Could be related to https://github.com/nmoinvaz/minizip/issues/137
If you run on android try to add `# define fopen64 fopen` somewhere in C code and compile native extension again (run `make` in gem folder)

**Comment by lsq** [comment]
Thanks！
