### ISSUE TITLE
Is there a way to "or" or add alignments?

### ISSUE THREAD

**Issue by davidw** [Paxa/fast_excel#3]
I would like to do:
```
fr.set(align: :align_center)
fr.set(align: :align_vertical_center)
```
Together - is there a way to do that that I'm missing?

**Comment by Paxa** [comment]
I added new `align()` and `align=()` methods with some shortcuts:

```ruby
format.align = {h: :center, v: :center}
```

https://github.com/Paxa/fast_excel/blob/master/examples/example_align.rb

**Comment by davidw** [comment]
@Paxa thank you!
