### ISSUE TITLE
is there any way to create a hyperlink inside a cell?

### ISSUE THREAD

**Issue by amfazlani** [Paxa/fast_excel#31]
Hi really awesome gem! I was wondering if there was any way to add a hyperlink url inside the cell I am currently using write_value but the value is only appearing as regular text. Thank you!

**Comment by Paxa** [comment]
Should be possible. I will prepare some example later, for now you may looks at https://github.com/jmcnamara/libxlsxwriter/blob/master/examples/hyperlinks.c

**Comment by amfazlani** [comment]
thank you so much!. I was checking those docs out earlier was having a tough time with the correct syntax in the ruby gem. Would really appreciate any examples.

**Comment by amfazlani** [comment]
Hi I was able to figure out how to url from the documentation you cited. Thank you for your help! I just had to use worksheet.write_url. Thank you.

**Comment by Paxa** [comment]
Added docs and special type `FastExcel::URL`

https://github.com/Paxa/fast_excel/commit/790242102bc34a5af90e3b3ba7fcbdf86b709cb2
