### ISSUE TITLE
Can you add automated column width?

### ISSUE THREAD

**Issue by Mikopet** [Paxa/fast_excel#4]
Hey!

I like your code to generate excel reports with high amount of rows.
But can you make please the automated column width feature? :-)

It would be a great feature.

Thanks!

**Comment by Paxa** [comment]
It would be hard to make and there will be big performance degradation.
Excel format don't have auto-width option, so it must be calculated by library, it means we need to predict content size for each cell, including custom format and formulas

I usually specify manually it works well in most of cases.

Do you have any better way how to implement it?

**Comment by Mikopet** [comment]
Yes, I have an idea. Maybe on write_row you can calculate the widths and save the values somewhere. So at the end - or maybe in runtime - the lib can adjust it.
Maybe we can set it at the `FastExcel.open('asd.xlsx', auto_width: true)`, so needless to write more code lines.

The other solution is to check the LibreOffice code, beacuse it makes this stuff very fast on large amount too. (I tried with 675k lines, and it lasts about a few miliseconds)

**Comment by Paxa** [comment]
It would be nice to have, but very difficult to make it work correctly in all situations. I don't want to include feature that works only in some situations.

But if you know what is font size and font type, then you can be done for plain text.
Easiest case when we use monospace font, for other fonts will need each characters' width

```ruby
require_relative '../lib/fast_excel'

workbook = FastExcel.open("example_auto_width.xlsx", constant_memory: true)

workbook.default_format.set(
  font_size: 12,
  font_family: "Arial"
)

worksheet = workbook.add_worksheet

lines = [
  "Lorem",
  "ipsum dolor sit amet,",
  "consectetur adipiscing elit",
  "sed do eiusmod tempor",
  #"incididunt ut labore et dolore magna aliqua",
  #"WWW_MMM_EEE_WWW_MMM_EEE_WWW_MMM_EEE",
]

lines.each_with_index do |line, index|
  worksheet.write_row(index, [line, line])
end

# numbers found somewhere on internet

char_widths = {
  ' ' => 0.6, ',' => 0.65, 'q' => 1.6, 'Q' => 2.34, '_' => 1.42,
  '.' => 1, 'a' => 1.73, 'b' => 1.8, 'c' => 1.51, 'd' => 1.8, 'e' => 1.73, 'f' => 1.05, 'g' => 1.8,
  'h' => 1.82, 'i' => 0.78, 'j' => 0.93, 'k' => 1.64, 'l' => 0.78, 'ł' => 0.93, 'm' => 2.73,
  'n' => 1.82, 'o' => 1.78, 'p' => 1.8, 'r' => 1.2, 's' => 1.45, 't' => 1.11, 'u' => 1.82,
  'w' => 2.91, 'x' => 1.62, 'y' => 1.64, 'z' => 1.45, '0' => 1.78, '1' => 1.78, '2' => 1.78,
  '3' => 1.78, '4' => 1.78, '5' => 1.78, '6' => 1.78, '7' => 1.78, '8' => 1.78, '9' => 1.78,
  'A' => 1.96, 'B' => 1.91, 'C' => 1.96, 'D' => 2.2, 'E' => 1.84, 'F' => 1.71, 'G' => 2.18,
  'H' => 2.2, 'I' => 1.22, 'J' => 1.36, 'Ł' => 1.69, 'K' => 1.91, 'L' => 1.63, 'M' => 2.51,
  'N' => 2.16, 'O' => 2.31, 'P' => 1.8, 'R' => 2.02, 'S' => 1.82, 'T' => 2.09, 'U' => 2.15,
  'W' => 2.93, 'X' => 1.91, 'Y' => 1.89, 'Z' => 1.82, '(' => 1.2, ')' => 1.2, '-' => 1.2,
  '–' => 1.8, '—' => 2.93
}

max_length = lines.map do |line|
  sum = 0
  line.each_char do |char|
    raise "missing #{char}" unless char_widths[char]
    sum += char_widths[char]
  end
  #p [line, sum]
  sum
end.max

worksheet.set_column_width(0, max_length * 0.55)  # 0.55 is calculated from my experiments

# code from axslx, but I may use it wrongly

THIN_CHARS = '^.acfijklrstxzFIJL()-'.freeze

def string_width(string, font_size)
  font_scale = font_size / 10.0
  (string.to_s.count(THIN_CHARS) + 3.0) * font_scale
end

max_length2 = lines.map do |line|
  string_width(line, 12)
end.max

p max_length2

worksheet.set_column_width(1, max_length2 * 0.873) # 0.873 is calculated from my experiments

workbook.close
puts "Saved to file example_auto_width.xlsx"
```

first solution works but not always correctly

---

If you find any solution that works well for you, please share

**Comment by Mikopet** [comment]
I dont know C very well,  so I cant port the logic from LibreOffice (or find it), but I think it may be the way for solution

Anyway thanks for looking around!

**Comment by AlexWayfer** [comment]
Did you see that: [Change the column width to automatically fit the contents (AutoFit)](https://support.office.com/en-us/article/Change-the-column-width-and-row-height-72f5e3cc-994d-43e8-ae58-9774a0905f46)? 🤔

**Comment by Paxa** [comment]
I dont know C very well too. 
I guess it use some function provided by system that renders all the text on a screen, just a guess.

Axslx used rmagick lib (binding to imagemagick) before to check size of each cell

**Comment by AlexWayfer** [comment]
Okay, proof of lacking this function in C library: [[1]](https://github.com/jmcnamara/libxlsxwriter/blob/723b5f750852c54e87f0ffffc39f24e0e6db5591/include/xlsxwriter/worksheet.h#L1139-L1143), [[2]](https://github.com/jmcnamara/libxlsxwriter/blob/8dc5f5420b299721020196e4ca23a575b5f3a676/docs/src/faq.dox#L53-L58). :pensive:

**Comment by AlexWayfer** [comment]
So… Probably, this issue doesn't for this gem :man_shrugging:

**Comment by davidw** [comment]
See note about axslx here: https://github.com/Paxa/fast_excel/issues/8

**Comment by davidw** [comment]
I think having the option to do what axslx does is better than nothing: axslx produces something that looks pretty good in most cases, whereas this gem's output is kind of squished by default.

**Comment by AlexWayfer** [comment]
[Two variants of realization in Perl](https://metacpan.org/pod/Spreadsheet::WriteExcel::Examples#Example:-autofit.pl).

The second (with TTF library) doesn't look too bad.

**Comment by davidw** [comment]
Quick thought: having a column that's a little bit 'too wide' is a lot better than having it scrunched up or cut off looking, in some cases.  Meaning you could probably just grab the font scale and multiply it by the number of letters and it'd be better than having to set things yourself or have things look cut off.

**Comment by Paxa** [comment]
Let's continue discussion in PR https://github.com/Paxa/fast_excel/pull/14
