### ISSUE TITLE
Append rows without keeping track of row number

### ISSUE THREAD

**Issue by davidw** [Paxa/fast_excel#5]
It'd be nice to be able to simply do

`sheet.append_row(data, some_style)`

and have the library keep track of the row number.

**Comment by Paxa** [comment]
Yes, gonna be nice, will add later

**Comment by Paxa** [comment]
Added in https://github.com/Paxa/fast_excel/commit/5a1e053614ea855abcf475db13f028ac1ccb595f

Please verify

**Comment by davidw** [comment]
Looks good, thank you!
