### ISSUE TITLE
set(:bg_color: 0xff0000) does not work

### ISSUE THREAD

**Issue by davidw** [Paxa/fast_excel#6]
This does not work:
`header_format.set(bg_color: 0xff0000)`
It neither sets the color, nor fails with an error.
Naturally, this works ok, but it's convenient to set a lot of things at once:
`header_format.set_bg_color(0xff0000)`

**Comment by AlexWayfer** [comment]
Just a remark: [`bg_collor=()` is better, than `set_bg_color()`](https://github.com/bbatsov/ruby-style-guide#accessor_mutator_method_names).

**Comment by Paxa** [comment]
Thanks for noticing, fixed

https://github.com/Paxa/fast_excel/blob/master/examples/example_colors.rb
