### ISSUE TITLE
undefined method `enable_filters!'

### ISSUE THREAD

**Issue by davidebettio** [Paxa/fast_excel#60]
Hi,
if I run the file `examples/example_filters.rb` (with `require('fast_excel')` instead of `require_relative '../lib/fast_excel'` I receive this error:

`undefined method enable_filters! for #<Libxlsxwriter::Worksheet:0x00007fa4c695a750> (NoMethodError)`

**Comment by Paxa** [comment]
Because new version is not released yet. You may use it from git
