### ISSUE TITLE
Not obvious - or possible - how to make columns fit contents

### ISSUE THREAD

**Issue by davidw** [Paxa/fast_excel#8]
I did see this in the libxsltwriter FAQ though:

https://libxlsxwriter.github.io/faq.html

> Unfortunately, there is no way to specify "AutoFit" for a column in the Excel file format. This feature is only available at runtime from within Excel. It is possible to simulate "AutoFit" by tracking the width of the data in the column as your write it.

It looks like axlsx does this:

```
    # This is still not perfect...
    #  - scaling is not linear as font sizes increst
    #  - different fonts have different mdw and char widths
    def autowidth
      return if is_formula? || value == nil
      mdw = 1.78 #This is the widest width of 0..9 in arial@10px)
      font_scale = (font_size/10.0).to_f
      ((value.to_s.count(Worksheet.thin_chars) * mdw + 5) / mdw * 256) / 256.0 * font_scale
    end
```

**Comment by Paxa** [comment]
Same as https://github.com/Paxa/fast_excel/issues/4

We can use same approach as axlsx, but it will not work with other fonts, custom formats (dates, currencies, number formats) and formulas
