### ISSUE TITLE
No such file libxlsxwriter on Ruby 3.2.0

### ISSUE THREAD

**Issue by guillaumewrobel** [Paxa/fast_excel#88]
Hello there

fast_excel v0.4.0
ruby v3.2.0

Since ruby 3.2.0, I get this error message when loading Rails:

> /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib':
Could not open library '/johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib':dlopen(/johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib, 0x0005): tried:
>- '/johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib' (no such file)
>- '/System/Volumes/Preboot/Cryptexes/OS/johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib' (no such file)
>- '/johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib' (no such file) (LoadError)
>        from /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
        from /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
        from /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/lib/fast_excel/binding.rb:16:in `<module:Libxlsxwriter>'
        from /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/lib/fast_excel/binding.rb:5:in `<main>'
        from /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/lib/fast_excel.rb:1:in `require_relative'
        from /johndoe/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/lib/fast_excel.rb:1:in `<main>'

**Comment by ezijlstra** [comment]
I have something similar with older ruby: libxlsxwriter.so is missing from gem directory:

```
# ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a)+jemalloc [x86_64-linux]

# bundle platform
Your platform is: x86_64-linux
 
# bundle install
Installing fast_excel 0.3.0 with native extensions
...
Bundle complete! 58 Gemfile dependencies, 175 gems now installed.
Bundled gems are installed into `/opt/bundle`

 
# rails c
/opt/bundle/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/opt/bundle/gems/fast_excel-0.3.0/libxlsxwriter/lib/libxlsxwriter.so': /opt/bundle/gems/fast_excel-0.3.0/libxlsxwriter/lib/libxlsxwriter.so: cannot open shared object file: No such file or directory (LoadError)
 
#  ls /opt/bundle/gems/fast_excel-0.3.0/libxlsxwriter/lib/
.. empty! ..
```

**Comment by brenogazzola** [comment]
Quick debug indicates that the dynamic lib to the library is not being generated during install on 3.2:
```
file 3.1.2/lib/ruby/gems/3.1.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib                                                                                               
# 3.1.2/lib/ruby/gems/3.1.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib: Mach-O 64-bit dynamically linked shared library x86_64

file 3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib                                                                                               
# 3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib: cannot open `3.2.0/lib/ruby/gems/3.2.0/gems/fast_excel-0.4.0/libxlsxwriter/lib/libxlsxwriter.dylib' (No such file or directory)
```

Wonder if install is failing somewhere because the `fiddle` gem no longer bundles libffi in 3.2?

**Comment by vladimirtemnikov** [comment]
Newest rubygems cleans all build artifacts after bundling.
https://github.com/rubygems/rubygems/issues/6205

**Comment by vladimirtemnikov** [comment]
Currently right after bundling `make clean -C libxlsxwriter` is called, so all artifacts are gone immediately.
@Paxa could we get rid of cleaning libxlsxwriter folder in main Makefile?

**Comment by cmer** [comment]
You can use my branch until [my pull request](https://github.com/Paxa/fast_excel/pull/90) is merged:

`gem "fast_excel", github: "cmer/fast_excel", branch: "ruby-3.2-compatibility"`

**Comment by sly7-7** [comment]
> Newest rubygems cleans all build artifacts after bundling. [rubygems/rubygems#6205](https://github.com/rubygems/rubygems/issues/6205)

from this issue, I understand that the built libxlsxwriter should be move to some extension_dir before cleaning. see https://github.com/rubygems/rubygems/issues/6205#issuecomment-1367871417

Does anyone here know how this could be done ?
